//! # gnome-iris
//!
//! GTK4 + Relm4 GUI for managing `ReShade` under Wine/Proton on Linux.

use std::io::Write;

use anyhow::Result;
use relm4::gtk::{gdk, gio};
use relm4::{RELM_THREADS, RelmApp, gtk};

use crate::ui::window::Window;

#[allow(missing_docs)]
#[allow(clippy::doc_markdown)]
/// Icon names generated by relm4-icons-build.
pub mod icon_names {
    pub use shipped::*;
    include!(concat!(env!("OUT_DIR"), "/icon_names.rs"));
}

/// Localization module.
pub mod localization;
/// Domain logic module — re-exported from the `gnome_iris` library crate.
pub use gnome_iris::reshade;
/// UI module.
pub mod ui;

/// D-Bus application ID. Must match the `GSettings` schema id and `GResource` prefix.
pub const APPLICATION_ID: &str = "org.gnome.Iris";

fn initialize_custom_resources() {
    gio::resources_register_include!("icons.gresources").unwrap();
    let display = gdk::Display::default().unwrap();
    let theme = gtk::IconTheme::for_display(&display);
    theme.add_resource_path("/org/gnome/Iris");
}

fn main() -> Result<()> {
    relm4_icons::initialize_icons(icon_names::GRESOURCE_BYTES, icon_names::RESOURCE_PREFIX);
    initialize_custom_resources();

    env_logger::builder()
        .format(|fmt, record| writeln!(fmt, "{}: {}", record.level(), record.args()))
        .init();

    localization::setup()?;

    RELM_THREADS.set(4).expect("Could not set thread count");

    let app = RelmApp::new(APPLICATION_ID);
    relm4::set_global_css("label.pill { border-radius: 9999px; padding: 2px 8px; }");
    app.run::<Window>(());

    Ok(())
}
